# Generated by Django 4.2.6 on 2023-11-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_alter_member_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Teen', 'Teen'), ('Sunday school', 'Sunday School'), ('Visitor', 'Visitor')], default='Adult', max_length=20),
        ),
    ]
